name: Test & Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
      TENDERLY_PROJECT_SLUG: ${{ secrets.TENDERLY_PROJECT_SLUG }}
      TENDERLY_ACCOUNT_ID: ${{ secrets.TENDERLY_ACCOUNT_ID }}
      DEBUG: true
    steps:
      - run: yarn install --immutable
      - run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install --immutable
      - run: yarn build
