# Build, Test, and Report
name: Build, Test, and Report

on:
  pull_request:
    branches:
      - main

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version
        run: yarn set version 4.5.0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Build
        run: yarn build
      
      - name: Run tests
        run: yarn test

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/
          retention-days: 15
