name: PR Title and Label Check
on:
  pull_request:
    # types: [opened, edited, labeled, unlabeled]
jobs:
  enforce-pr-naming:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Check PR Title follows conventional commit naming
        id: check-pr-naming
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        with:
          types: |
            major
            minor
            patch
            none
          ignoreLabels: |
            skip-ci
          requireScope: false
          wip: true
          validateSingleCommit: false

      - name: Check PR Labels are valid
        id: check-pr-labels
        continue-on-error: true
        run: |
          labels=$(echo "${{ github.event.pull_request.labels[*].name }}" | tr ' ' '\n')
          if ! echo "$labels" | grep -qE '^(major|minor|patch)$'; then
            echo "PR must have at least one of the following labels: major, minor, patch."
            echo "labels_valid=false" >> $GITHUB_OUTPUT
            # exit 1
          else
            echo "labels_valid=true" >> $GITHUB_OUTPUT
          fi

      - name: Add PR naming error comment
        id: pr-title-error
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hey there and thank you for opening this pull request! 👋🏼
            
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:
            
            ```
            ${{ steps.check-pr-naming.outputs.error_message }}
          edit-mode: replace
        if: steps.check-pr-naming.outputs.error_message != null

      - name: Add PR naming error comment
        id: pr-label-error
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            PR must have at least one of the following labels: major, minor, patch.
          edit-mode: replace
        if: steps.check-pr-labels.outputs.labels_valid == 'false'

      - name: Remove title error comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.pr-title-error.outputs.comment-id }}
          body: ""
          edit-mode: delete
        if: steps.check-pr-naming.outputs.error_message == null

      - name: Remove title error comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.pr-label-error.outputs.comment-id }}
          body: ""
          edit-mode: delete
        if: steps.check-pr-labels.outputs.labels_valid == 'true'

