name: Release and Versioning
on:
  pull_request:
    # types: [closed]
    # branches:
    #   - main
    paths:
      - '.github/workflows/prepare-release.yml'

jobs:
  get_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Highly security sensitive. Do NOT add third party actions in this job
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{${{ github.ref_name }} }}          
          fetch-depth: 0 # https://yarnpkg.com/features/release-workflow#caveat

      - name: Show current branch
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Current commit: $(git rev-parse HEAD)"
          git log --oneline -5          
          
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version
        run: yarn set version 4.5.0

      - name: Check PR version labels
        id: bump
        run: |
          # Check for version type labels
          if ${{ contains(github.event.pull_request.labels.*.name, 'major') }}; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif ${{ contains(github.event.pull_request.labels.*.name, 'patch') }}; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "type=no-release" >> $GITHUB_OUTPUT
          fi
          
          # Check for alpha label
          if ${{ contains(github.event.pull_request.labels.*.name, 'alpha') }}; then
            echo "alpha=true" >> $GITHUB_OUTPUT
            echo "type=prerelease" >> $GITHUB_OUTPUT
          else
            echo "alpha=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if no version bump
        id: cancel
        if: steps.bump.outputs.type == 'no-release'
        run: |
          echo "::warning::No version bump required. Skipping release steps."

      - name: Toggle Alpha
        if: steps.bump.outputs.type != 'no-release'
        run: |
          if [ "${{ steps.bump.outputs.alpha }}" == "true" ]; then
            ./.github/ci-scripts/toggle-alpha.sh yes
          else
            ./.github/ci-scripts/toggle-alpha.sh #remove alpha if present
          fi

      - name: Bump version
        if: steps.bump.outputs.type != 'no-release'
        run: yarn version ${{ steps.bump.outputs.type }}

      - name: Push changes
        if: steps.bump.outputs.type != 'no-release'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actionsbot@github.com'
          VERSION=$(node -p "require('./package.json').version")
          git add .
          git commit -am "Bump version to ${VERSION}"
          git push
          git push --tags
      
      - name: Create GitHub Release
        if: steps.bump.outputs.type != 'no-release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          gh release create "v${VERSION}" \
            --title "Release v${VERSION}" \
            --generate-notes \
            --prerelease \
            --draft
