name: Test & Build

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
      PROJECT_SLUG: ${{ secrets.PROJECT_SLUG }}
      ACCOUNT_SLUG: ${{ secrets.ACCOUNT_SLUG }}
      DEBUG: ${{ github.run_attempt > 1 }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version
        run: yarn set version 4.5.0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

  enforce-pr-naming:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            major
            minor
            patch
            none
          requireScope: false
          wip: true
          validateSingleCommit: false
